### ISSUE TITLE
opentx 2.3 number jumping back to another value

### ISSUE THREAD

**Issue by robschii** [betaflight/betaflight-tx-lua-scripts#245]
for example you want to switch vtx channel.......  number is jumping to the value before    or you hold the plus/minus button for a long time

**Comment by hsuq510** [comment]
sames here, it seems the EVT_MINUS_BREAK is not properly handled. Any value changed with the minus button on a X9D+ (not 2019) has the effect when release the minus button the value returns the previous without any effect.

step to reproduce:
select a value, change it with minus , release minus button , see value change back to what is was at first

**Comment by robschii** [comment]
nothing happend till now

**Comment by RipperDrone** [comment]
https://github.com/opentx/opentx/issues/6852#issuecomment-538082073

**Comment by RipperDrone** [comment]
searched in ui.lua (not sure this is the right spot...) - looks ok so far doesn't it?
![image](https://user-images.githubusercontent.com/12601105/66157632-7a810e00-e624-11e9-9ec5-435f22a81c30.png)

**Comment by RipperDrone** [comment]
incValue() - is this part good?

![image](https://user-images.githubusercontent.com/12601105/66157748-b6b46e80-e624-11e9-9b73-ecadea22c929.png)

**Comment by hsuq510** [comment]
betaflight event.lua has the following:

    dial = {
        left = EVT_ROT_LEFT or EVT_UP_BREAK,
        right = EVT_ROT_RIGHT or EVT_DOWN_BREAK
    }

removing the OR condition make script to work properly. This is not an opentx issue.

**Comment by RipperDrone** [comment]
maybe the Horus or Taranis 2019 wheel commands are mixed up with the old button commands the wrong way...?

**Comment by hsuq510** [comment]
can you please test if this in the events.lua fix the issue ?

dial = {
    left = EVT_ROT_LEFT ,
    right = EVT_ROT_RIGHT
}

**Comment by RipperDrone** [comment]
No, it doesn't :-(

**Comment by mikeller** [comment]
This code was added in #135 by @raphaelcoeffic. Maybe he has got an idea what needs to be done here?
As it is now with these scripts, we are supporting a number of different hardware types with different switches / toggles / wheels, so we need to thread carefully and do thorough testing to make sure we don't just shift the breakage to different hardware.

**Comment by RipperDrone** [comment]
Yes, it does (I first kept the wrong half of the expression, thinking the ROT_ identifiers were supposed to fit the Taranis 2019 with ROTation wheel... :-))

So dropping the ROT_ parts of the OR expression does the trick on my Taranis 2013 X9D+

**Comment by hsuq510** [comment]
Yes, to me is working.

**Comment by RipperDrone** [comment]
Maybe the Taranis 2019 identifiers are pre-initialized to values which make the OR expression go wrong for a Taranis 2013?

**Comment by hsuq510** [comment]
well it seems like opentx 2.3 has wrongly assigned EVT_DOWN_BREAK assigned to minus

**Comment by raphaelcoeffic** [comment]
> As it is now with these scripts, we are supporting a number of different hardware types with different switches / toggles / wheels, so we need to thread carefully and do thorough testing to make sure we don't just shift the breakage to different hardware.

We have discussed this internally with the other opentx devs and it seems that some events have been broken for LUA since 2.3. We will need to look into it.

However, it should be time to think about moving to the new virtual events, which should normally bring compatibility with all radios with minimum effort.

**Comment by mikeller** [comment]
@raphaelcoeffic: You seem to be in the loop on OpenTX development, would you be able to propose a change to move to virtual events?

**Comment by raphaelcoeffic** [comment]
Yes, That’s the plan. I don’t have much hardware to test on, but I guess a lot of people are eager to test ;-)

**Comment by mikeller** [comment]
@raphaelcoeffic: Well, the hope would is that if we move to virtual events that are then mapped to hardware switches / wheels by OpenTX then the mapping to the different hardware types would have been done in OpenTX when they were added. :wink:

**Comment by raphaelcoeffic** [comment]
@mikeller that’s the idea, yes. The feature is already in OpenTx, so we need to adapt the key mapping, and that’s it.

**Comment by 3djc** [comment]
I just reviewed the virtual events to make a difference between INC/DEC for changing value, and PREV/NEXT for navigating the UI, since x9d(+) has those reversed. Should be merged shortly

**Comment by mikeller** [comment]
@3djc: I like that. Can you alert us / propose a change when the fix for X9D+ has been merged - I think a considerable part of our users are using this hardware.

**Comment by RipperDrone** [comment]
@mikeller @raphaelcoeffic Here it is: https://github.com/opentx/opentx/pull/6890 (thank you @3djc !) :-)

**Comment by raphaelcoeffic** [comment]
first PoC for the virtual events: #250

**Comment by mikeller** [comment]
@raphaelcoeffic, @3djc: Any chance that this is fixed in 2.3.1?
If so I think the right thing to do is to release a version of the lua scripts that include the changes needed for Betaflight 4.1 now, and tell users to update to OpenTX 2.3.1.
This will then allow us to give the 'virtual events' changes in #250 some weeks time for thorough testing / feedback, and after that we can do another release that includes them.
Thoughts?

**Comment by raphaelcoeffic** [comment]
@mikeller Just added #251 for this purpose, let's see if that works better. It does for me on the simulator, but I don't have any X9D+ for testing in real...

**Comment by RipperDrone** [comment]
no, not resolved yet on X9D+ ... https://github.com/betaflight/betaflight-tx-lua-scripts/issues/255
